INSERT INTO instrumentos (id, nombre, tipo) VALUES (1, 'clarinete', 'viento-madera');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Jorge', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Cris', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Mama', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Papa', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Ejempl', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Nose', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Nose2', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('JJ', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Jorge', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Cris', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Mama', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Papa', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Ejempl', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Nose', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Nose2', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('JJ', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Jorge', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Cris', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Mama', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Papa', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Ejempl', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Nose', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('Nose2', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');
INSERT INTO componentes (nombre, apellido, direccion, email, sexo, dni, instrumento_id, create_at) VALUES ('JJ', 'Doe','mi calle', 'micorreo', 'masculino','47536486V', 1, '2017-08-28');

INSERT INTO tipo_marchas (id, nombre, descripcion) VALUES (1, 'funebre', '');
INSERT INTO tipo_marchas (id, nombre, descripcion) VALUES (2, 'ccytt', '');

INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('A ti Manué', 'Juan José Puntas','2015-01-01', '2015-01-01',1);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Al Cielo con Ella', 'Pedro Morales','2015-01-01', '2015-01-01',2);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Al cielo la Paz', 'J.J. Espinosa de los Monteros','2015-01-01', '2015-01-01',1);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Alma de la Trinidad', 'Eloy García','2015-01-01', '2015-01-01',2);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Amarguras', 'Manuel Font de Anta','2015-01-01', '2015-01-01',1);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Aniversario Macareno', 'José Velazquez','2015-01-01', '2015-01-01',2);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Aquella Virgen', 'Manuel Gomez de Arriba','2015-01-01', '2015-01-01',1);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Candelaria', 'Manuel Marvizon','2015-01-01', '2015-01-01',2);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Como Tú, ninguna', 'David Hurtado','2015-01-01', '2015-01-01',1);
INSERT INTO marchas (nombre, compositor, fecha_creacion, fecha_alta, tipo_id) VALUES ('Cordero de Dios', 'Ricardo Dorado','2015-01-01', '2015-01-01',2);